name = "CineFiles"
uuid = "56ba7af4-1aa7-4a85-af25-aa88a55212a9"
authors = ["Alex Ames <alexander.m.ames@gmail.com> and contributors"]
version = "0.1.2"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"

[compat]
ColorTypes = "0.10, 0.11"
LRUCache = "1.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
